<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('currencies')->insert([
            ['code' => 'AFN', 'name' => 'Afghani', 'symbol' => '؋', 'decimals' => 2],
            ['code' => 'ALL', 'name' => 'Lek', 'symbol' => 'Lek', 'decimals' => 2],
            ['code' => 'ANG', 'name' => 'Netherlands Antillian Guilder', 'symbol' => 'ƒ', 'decimals' => 2],
            ['code' => 'ARS', 'name' => 'Argentine Peso', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'AUD', 'name' => 'Australian Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'AWG', 'name' => 'Aruban Guilder', 'symbol' => 'ƒ', 'decimals' => 2],
            ['code' => 'AZN', 'name' => 'Azerbaijanian Manat', 'symbol' => 'ман', 'decimals' => 2],
            ['code' => 'BAM', 'name' => 'Convertible Marks', 'symbol' => 'KM', 'decimals' => 2],
            ['code' => 'BDT', 'name' => 'Bangladeshi Taka', 'symbol' => '৳', 'decimals' => 2],
            ['code' => 'BBD', 'name' => 'Barbados Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'BGN', 'name' => 'Bulgarian Lev', 'symbol' => 'лв', 'decimals' => 2],
            ['code' => 'BMD', 'name' => 'Bermudian Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'BND', 'name' => 'Brunei Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'BOB', 'name' => 'BOV Boliviano Mvdol', 'symbol' => '$b', 'decimals' => 2],
            ['code' => 'BRL', 'name' => 'Brazilian Real', 'symbol' => 'R$', 'decimals' => 2],
            ['code' => 'BSD', 'name' => 'Bahamian Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'BWP', 'name' => 'Pula', 'symbol' => 'P', 'decimals' => 2],
            ['code' => 'BYR', 'name' => 'Belarussian Ruble', 'symbol' => '₽', 'decimals' => 2],
            ['code' => 'BZD', 'name' => 'Belize Dollar', 'symbol' => 'BZ$', 'decimals' => 2],
            ['code' => 'CAD', 'name' => 'Canadian Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'CHF', 'name' => 'Swiss Franc', 'symbol' => 'CHF', 'decimals' => 2],
            ['code' => 'CLP', 'name' => 'CLF Chilean Peso Unidades de fomento', 'symbol' => '$', 'decimals' => 0],
            ['code' => 'CNY', 'name' => 'Yuan Renminbi', 'symbol' => '¥', 'decimals' => 2],
            ['code' => 'COP', 'name' => 'COU Colombian Peso Unidad de Valor Real', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'CRC', 'name' => 'Costa Rican Colon', 'symbol' => '₡', 'decimals' => 2],
            ['code' => 'CUP', 'name' => 'CUC Cuban Peso Peso Convertible', 'symbol' => '₱', 'decimals' => 2],
            ['code' => 'CZK', 'name' => 'Czech Koruna', 'symbol' => 'Kč', 'decimals' => 2],
            ['code' => 'DKK', 'name' => 'Danish Krone', 'symbol' => 'kr', 'decimals' => 2],
            ['code' => 'DOP', 'name' => 'Dominican Peso', 'symbol' => 'RD$', 'decimals' => 2],
            ['code' => 'EGP', 'name' => 'Egyptian Pound', 'symbol' => '£', 'decimals' => 2],
            ['code' => 'EUR', 'name' => 'Euro', 'symbol' => '€', 'decimals' => 2],
            ['code' => 'FJD', 'name' => 'Fiji Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'FKP', 'name' => 'Falkland Islands Pound', 'symbol' => '£', 'decimals' => 2],
            ['code' => 'GBP', 'name' => 'Pound Sterling', 'symbol' => '£', 'decimals' => 2],
            ['code' => 'GIP', 'name' => 'Gibraltar Pound', 'symbol' => '£', 'decimals' => 2],
            ['code' => 'GTQ', 'name' => 'Quetzal', 'symbol' => 'Q', 'decimals' => 2],
            ['code' => 'GYD', 'name' => 'Guyana Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'HKD', 'name' => 'Hong Kong Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'HNL', 'name' => 'Lempira', 'symbol' => 'L', 'decimals' => 2],
            ['code' => 'HRK', 'name' => 'Croatian Kuna', 'symbol' => 'kn', 'decimals' => 2],
            ['code' => 'HUF', 'name' => 'Forint', 'symbol' => 'Ft', 'decimals' => 2],
            ['code' => 'IDR', 'name' => 'Rupiah', 'symbol' => 'Rp', 'decimals' => 2],
            ['code' => 'ILS', 'name' => 'New Israeli Sheqel', 'symbol' => '₪', 'decimals' => 2],
            ['code' => 'IRR', 'name' => 'Iranian Rial', 'symbol' => '﷼', 'decimals' => 2],
            ['code' => 'ISK', 'name' => 'Iceland Krona', 'symbol' => 'kr', 'decimals' => 0],
            ['code' => 'JMD', 'name' => 'Jamaican Dollar', 'symbol' => 'J$', 'decimals' => 2],
            ['code' => 'JPY', 'name' => 'Yen', 'symbol' => '¥', 'decimals' => 0],
            ['code' => 'KGS', 'name' => 'Som', 'symbol' => 'лв', 'decimals' => 2],
            ['code' => 'KHR', 'name' => 'Riel', 'symbol' => '៛', 'decimals' => 2],
            ['code' => 'KPW', 'name' => 'North Korean Won', 'symbol' => '₩', 'decimals' => 2],
            ['code' => 'KRW', 'name' => 'Won', 'symbol' => '₩', 'decimals' => 0],
            ['code' => 'KYD', 'name' => 'Cayman Islands Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'KZT', 'name' => 'Tenge', 'symbol' => 'лв', 'decimals' => 2],
            ['code' => 'LAK', 'name' => 'Kip', 'symbol' => '₭', 'decimals' => 0],
            ['code' => 'LBP', 'name' => 'Lebanese Pound', 'symbol' => '£', 'decimals' => 2],
            ['code' => 'LKR', 'name' => 'Sri Lanka Rupee', 'symbol' => '₨', 'decimals' => 2],
            ['code' => 'LRD', 'name' => 'Liberian Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'LTL', 'name' => 'Lithuanian Litas', 'symbol' => 'Lt', 'decimals' => 2],
            ['code' => 'LVL', 'name' => 'Latvian Lats', 'symbol' => 'Ls', 'decimals' => 2],
            ['code' => 'MAD', 'name' => 'Moroccan Dirham', 'symbol' => 'Dhs', 'decimals' => 2],
            ['code' => 'MKD', 'name' => 'Denar', 'symbol' => 'ден', 'decimals' => 2],
            ['code' => 'MNT', 'name' => 'Tugrik', 'symbol' => '₮', 'decimals' => 2],
            ['code' => 'MUR', 'name' => 'Mauritius Rupee', 'symbol' => '₨', 'decimals' => 2],
            ['code' => 'MXN', 'name' => 'MXV Mexican Peso Mexican Unidad de Inversion (UDI]', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'MYR', 'name' => 'Malaysian Ringgit', 'symbol' => 'RM', 'decimals' => 2],
            ['code' => 'MZN', 'name' => 'Metical', 'symbol' => 'MT', 'decimals' => 2],
            ['code' => 'NGN', 'name' => 'Naira', 'symbol' => '₦', 'decimals' => 2],
            ['code' => 'NIO', 'name' => 'Cordoba Oro', 'symbol' => 'C$', 'decimals' => 2],
            ['code' => 'NOK', 'name' => 'Norwegian Krone', 'symbol' => 'kr', 'decimals' => 2],
            ['code' => 'NPR', 'name' => 'Nepalese Rupee', 'symbol' => '₨', 'decimals' => 2],
            ['code' => 'NZD', 'name' => 'New Zealand Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'OMR', 'name' => 'Rial Omani', 'symbol' => '﷼', 'decimals' => 3],
            ['code' => 'PAB', 'name' => 'USD Balboa US Dollar', 'symbol' => 'B/.', 'decimals' => 2],
            ['code' => 'PEN', 'name' => 'Nuevo Sol', 'symbol' => 'S/.', 'decimals' => 2],
            ['code' => 'PHP', 'name' => 'Philippine Peso', 'symbol' => 'Php', 'decimals' => 2],
            ['code' => 'PKR', 'name' => 'Pakistan Rupee', 'symbol' => '₨', 'decimals' => 2],
            ['code' => 'PLN', 'name' => 'Zloty', 'symbol' => 'zł', 'decimals' => 2],
            ['code' => 'PYG', 'name' => 'Guarani', 'symbol' => 'Gs', 'decimals' => 0],
            ['code' => 'QAR', 'name' => 'Qatari Rial', 'symbol' => '﷼', 'decimals' => 2],
            ['code' => 'RON', 'name' => 'New Leu', 'symbol' => 'lei', 'decimals' => 2],
            ['code' => 'RSD', 'name' => 'Serbian Dinar', 'symbol' => 'Дин.', 'decimals' => 2],
            ['code' => 'RUB', 'name' => 'Russian Ruble', 'symbol' => 'руб', 'decimals' => 2],
            ['code' => 'SAR', 'name' => 'Saudi Riyal', 'symbol' => '﷼', 'decimals' => 2],
            ['code' => 'SBD', 'name' => 'Solomon Islands Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'SCR', 'name' => 'Seychelles Rupee', 'symbol' => '₨', 'decimals' => 2],
            ['code' => 'SEK', 'name' => 'Swedish Krona', 'symbol' => 'kr', 'decimals' => 2],
            ['code' => 'SGD', 'name' => 'Singapore Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'SHP', 'name' => 'Saint Helena Pound', 'symbol' => '£', 'decimals' => 2],
            ['code' => 'SOS', 'name' => 'Somali Shilling', 'symbol' => 'S', 'decimals' => 2],
            ['code' => 'SRD', 'name' => 'Surinam Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'SVC', 'name' => 'USD El Salvador Colon US Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'SYP', 'name' => 'Syrian Pound', 'symbol' => '£', 'decimals' => 2],
            ['code' => 'THB', 'name' => 'Baht', 'symbol' => '฿', 'decimals' => 2],
            ['code' => 'TRY', 'name' => 'Turkish Lira', 'symbol' => 'TL', 'decimals' => 2],
            ['code' => 'TTD', 'name' => 'Trinidad and Tobago Dollar', 'symbol' => 'TT$', 'decimals' => 2],
            ['code' => 'TWD', 'name' => 'New Taiwan Dollar', 'symbol' => 'NT$', 'decimals' => 2],
            ['code' => 'UAH', 'name' => 'Hryvnia', 'symbol' => '₴', 'decimals' => 2],
            ['code' => 'USD', 'name' => 'US Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'UYU', 'name' => 'UYI Uruguay Peso en Unidades Indexadas', 'symbol' => '$U', 'decimals' => 0],
            ['code' => 'UZS', 'name' => 'Uzbekistan Sum', 'symbol' => 'лв', 'decimals' => 2],
            ['code' => 'VEF', 'name' => 'Bolivar Fuerte', 'symbol' => 'Bs', 'decimals' => 2],
            ['code' => 'VND', 'name' => 'Dong', 'symbol' => '₫', 'decimals' => 2],
            ['code' => 'XCD', 'name' => 'East Caribbean Dollar', 'symbol' => '$', 'decimals' => 2],
            ['code' => 'YER', 'name' => 'Yemeni Rial', 'symbol' => '﷼', 'decimals' => 2],
            ['code' => 'ZAR', 'name' => 'Rand', 'symbol' => 'R', 'decimals' => 2],
        ]);
    }
}
